import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar";
import styles from "@/styles/header.module.scss";

const mulish = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Juan dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <header className={styles.header}>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
