import type { Metadata } from "next";
import { Toaster } from "sonner";
import { Mulish } from "next/font/google";
import StarsBackground from "@/components/Stars";
import Provider from "@/context/Provider";
import styles from "@/styles/header.module.scss";
import Navbar from "@/components/navbar/Navbar";
import "@/styles/globals.css";

const mulish = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Juan dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Provider>
          <StarsBackground />
          <header className={styles.header}>
            <Navbar />
          </header>
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
